export enum PaymentStatus {
  CREATED = "CREATED",
  PENDING = "PENDING",
  IN_PROGRESS = "IN_PROGRESS",
  AUTHORIZED = "AUTHORIZED",
  FAILED = "FAILED",
  COMPLETED = "COMPLETED",
  CANCELED = "CANCELED",
  REFUNDED = "REFUNDED",
}
